### ISSUE TITLE
Encrypting a string of length blocksize crashes

### ISSUE THREAD

**Issue by jaraco** [dsoprea/RijndaelPbkdf#2]
Consider this simple script:

```
__requires__ = ['pprp']

import pprp
plaintext = 'a' * 32
sg = pprp.data_source_gen(plaintext.encode('utf-8'), block_size=32)
padded_key = b'\00' * 24
eg = pprp.rjindael_encrypt_gen(padded_key, sg, block_size=32)
list(eg)
```

Run it with pprp installed or with [rwt]:

```
$ rwt -- test-pprp.py 
Collecting pprp
  Using cached pprp-0.2.5-py3-none-any.whl
Installing collected packages: pprp
Successfully installed pprp-0.2.5
Traceback (most recent call last):
  File "test-pprp.py", line 8, in <module>
    list(eg)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-dpcspqam/pprp/adapters.py", line 29, in rjindael_encrypt_gen
    yield r.encrypt(chr(block_size) * block_size)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-dpcspqam/pprp/crypto_3.py", line 321, in encrypt
    plaintext[i * 4 + 2] <<  8 |
TypeError: unsupported operand type(s) for <<: 'str' and 'int'
```

**Comment by jaraco** [comment]
Thanks for this. Any chance of a published release as well?

**Comment by jaraco** [comment]
We've been using the code from the PR for some time now.
