### ISSUE TITLE
encrypt_sink fails requiring "a bytes-like object"

### ISSUE THREAD

**Issue by ashokdelphia** [dsoprea/RijndaelPbkdf#9]
Adjusting the example in the readme to encrypt the data, I get the following error in a vanilla Python 3.7 virtual env, having run `pip install pprp==0.2.7`:

```
Python 3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pprp
>>> passphrase = 'password'.encode('ASCII')
>>> salt = 'salt'.encode('ASCII')
>>> 
>>> key_size = 32
>>> data = "this is a test" * 100
>>> data_bytes = data.encode('ASCII')
>>> 
>>> key = pprp.pbkdf2(passphrase, salt, key_size)
>>> 
>>> # Create a source from available data.
>>> sg = pprp.data_source_gen(data_bytes)
>>> 
>>> # Feed the source into the encryptor.
>>> eg = pprp.rijndael_encrypt_gen(key, sg)
>>> pprp.encrypt_sink(eg)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/…/venv/lib/python3.7/site-packages/pprp/sink.py", line 24, in encrypt_sink
    s.write(block)
TypeError: a bytes-like object is required, not 'str'
```

I get a similar error in a real project I'm trying to upgrade from 0.2.6 to 0.2.7.

In 0.2.6, `eg` produces a list of bytearrays:

```
>>> eg = pprp.rjindael_encrypt_gen(key, sg)
>>> [block for block in eg]
[bytearray(b'gg\xf3\x94\xc9/;\xdd\x01\xaaW\xdcc+A\xae'), bytearray(b'$;\xc7C\xbe\x94\x86\xa7n\x1d\x02^m\x0c\xff\xc0'), …]
```

Whereas in 0.2.7 it produces a list of strings for me:

```
>>> eg = pprp.rijndael_encrypt_gen(key, sg)
>>> [block for block in eg]
['ggó\x94É/;Ý\x01ªWÜc+A®', '$;ÇC¾\x94\x86§n\x1d\x02^m\x0cÿÀ', …]
```

**Comment by brainstormtrooper** [comment]
would something like this be ok as a workaround?

```
egba = [block.encode('utf-8') for block in eg]
ciphertext = pprp.encrypt_sink(egba)
```

**Comment by jaraco** [comment]
This regression has also broken the example I gave in [this SO answer](https://stackoverflow.com/a/45653735/70170). Surely a bugfix release shouldn't introduce a regression or at the very least should be addressed promptly?
